// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcUDDWY4pfoGmNt5dc2csz6ZVb-0ANSdU',
    appId: '1:796368805205:web:b21a270ffe41b65b5f63dc',
    messagingSenderId: '796368805205',
    projectId: 'personality-scale-c53bc',
    authDomain: 'personality-scale-c53bc.firebaseapp.com',
    storageBucket: 'personality-scale-c53bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1qv_guwO5Njns5kW1u9j_7MxhpYiv2dg',
    appId: '1:796368805205:android:aaf2d757b44d509a5f63dc',
    messagingSenderId: '796368805205',
    projectId: 'personality-scale-c53bc',
    storageBucket: 'personality-scale-c53bc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcUDDWY4pfoGmNt5dc2csz6ZVb-0ANSdU',
    appId: '1:796368805205:web:d6cbbaffae621f825f63dc',
    messagingSenderId: '796368805205',
    projectId: 'personality-scale-c53bc',
    authDomain: 'personality-scale-c53bc.firebaseapp.com',
    storageBucket: 'personality-scale-c53bc.firebasestorage.app',
  );
}
